[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[scheduled-functions]]
  name = "scheduled-backup"
  cron = "0 8,11,16 * * *"
